language: python

notifications:      # 邮箱通知
  email: false

env:
  - RTT_BSP='CME_M7' RTT_TOOL_CHAIN='sourcery-arm'

jobs:
  include:
    - stage: compile
      rvm: 1
      script: python tools/build-A.py $RTT_BSP $RTT_TOOL_CHAIN
    - stage: compile
      rvm: 2
      script: false
    - stage: AutoTest
      rvm: 3
      script: python tools/autotest.py $RTT_BSP $RTT_TOOL_CHAIN
  allow_failures:
    - rvm: 2
