language: python

notifications:      # 邮箱通知
  email: false

env:
  - RTT_BSP='CME_M7' RTT_TOOL_CHAIN='sourcery-arm'

jobs:
  include:
    - stage: AutoTest
      rvm: 3
      script: 
        - echo "helloworld"
        - curl --help
