language: python

notifications:      # 邮箱通知
  email: false

env:
  - RTT_BSP='CME_M7' RTT_TOOL_CHAIN='sourcery-arm'

jobs:
  include:
    - stage: build
      script: python tools/build-A.py $RTT_BSP $RTT_TOOL_CHAIN
    - # stage name not required, will continue to use `test`
      script: python tools/build-A.py $RTT_BSP $RTT_TOOL_CHAIN
    - stage: AutoTest
      script: python tools/autotest.py $RTT_BSP $RTT_TOOL_CHAIN
