language: python
python: "2.7"

before_script:
    - date
    - echo "before_script"
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_ID
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_EVENT_TYPE
    - echo ${TRAVIS_PULL_REQUEST}
    - echo ${TRAVIS_PULL_REQUEST_BRANCH}
    - echo ${TRAVIS_PULL_REQUEST_SHA}

# check 'TRAVIS_EVENT_TYPE'
# check PR if is opened

script:
    - echo "script"
    - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
        echo "PR mode";
        curl --request POST 
            --header "PRIVATE-TOKEN:FwFiiCvzHsMQ7y12mX9g" 
            --header "Content-Type:application/json" 
            --data '{"ref":"master","variables":[{"key":"GITHUB_PR_NUMBER","value":"$TRAVIS_PULL_REQUEST"},{"key":"GITHUB_DEFAULT_BRANCH","value":"master"},{"key":"GITHUB_MERGE_SHA","value":"414cb0069601a32b00bd122a2380cd283626a8e5"},{"key":"GITHUB_HEAD_SHA","value":"414cb0069601a32b00bd122a2380cd283626a8e5"}]}' 
            "http://183.193.243.90:666/api/v4/projects/3/pipeline?ref=master"
      else
        echo "not PR mode";
      fi
