language: python
python: "2.7"

before_script:
    - date
    - echo "before_script"

script:
    - echo "script"
    - curl --request POST 
        --header "PRIVATE-TOKEN:FwFiiCvzHsMQ7y12mX9g" --header "Content-Type:application/json" "http://183.193.243.90:666/api/v4/projects/3/pipeline?ref=master"