language: python
python: "2.7"

before_script:
    - date
    - echo "before_script"
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_ID
    - echo $TRAVIS_JOB_ID
    - echo $TRAVIS_JOB_NAME
    - echo $TRAVIS_JOB_NUMBER
    - echo $TRAVIS_JOB_WEB_URL
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_EVENT_TYPE
    - echo ${TRAVIS_PULL_REQUEST}
    - echo ${TRAVIS_PULL_REQUEST_BRANCH}
    - echo ${TRAVIS_PULL_REQUEST_SHA}

# check 'TRAVIS_EVENT_TYPE'
# check PR if is opened

script:
    - echo "script"
    - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
        echo "PR mode";
        curl --request POST 
            --header "PRIVATE-TOKEN:${GITLAB_ACCESS_TOKEN}" 
            --header "Content-Type:application/json" 
            --data '{"ref":"master","tag":"windows","variables":[{"key":"GITHUB_EVENT_TYPE","value":"'${TRAVIS_EVENT_TYPE}'"},{"key":"GITHUB_JOB_ID","value":"'${TRAVIS_BUILD_NUMBER}'"},{"key":"GITHUB_PR_NUMBER","value":"'${TRAVIS_PULL_REQUEST}'"},{"key":"GITHUB_DEFAULT_BRANCH","value":"'${TRAVIS_BRANCH}'"},{"key":"GITHUB_HEAD_SHA","value":"'${TRAVIS_PULL_REQUEST_SHA}'"}]}' 
            "http://183.193.243.90:666/api/v4/projects/3/pipeline?ref=master";
      else
        echo "not PR mode";
      fi
