language: python

notifications:      # 邮箱通知
  email: false

 matrix:
  include:
  - python: "2.7"
  env: RTT_BSP='stm32f429ig' RTT_TOOL_CHAIN='sourcery-arm'

script:
  - python tools/autotest.py $RTT_BSP $RTT_TOOL_CHAIN