language: python

notifications:      # 邮箱通知
  email: false

env:
  - RTT_BSP='CME_M7' RTT_TOOL_CHAIN='sourcery-arm'

jobs:
  include:
    - stage: compile
      rvm: 1
      script: python tools/build-A.py $RTT_BSP $RTT_TOOL_CHAIN
    - stage: compile
      rvm: 2
      script: false
    - stage: AutoTest
      rvm: 3
      script: 
        - curl --request POST --header "PRIVATE-TOKEN: FwFiiCvzHsMQ7y12mX9g" --header "Content-Type: application/json" --data '{ "ref": "master", "variables": [ {"key": "GITHUB_ACTION", "value": "opened"}, {"key": "GITHUB_PR_NUMBER", "value": "123"}, {"key": "GITHUB_DEFAULT_BRANCH", "value": "master"}, {"key": "GITHUB_MERGE_SHA", "value": "414cb0069601a32b00bd122a2380cd283626a8e5"}, {"key": "GITHUB_HEAD_SHA", "value": "414cb0069601a32b00bd122a2380cd283626a8e5"}] }' "http://183.193.243.90:666/api/v4/projects/3/pipeline"
  allow_failures:
    - rvm: 2
